application: zacharytamas
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: _site/index.html
  upload: _site/index.html

- url: /
  static_dir: _site/

libraries:
- name: jinja2
  version: latest

skip_files:
- node_modules/.*$
- bower_components/.*$
- dist/bower_components/(.*)\.md$
- (.*)\.sketch$
- libs/.*\.dist-info/.*$
